### ISSUE TITLE
Crash cuando no encuentra un usuario en el shared.

### ISSUE THREAD

**Issue by juanmanuelromeraferrio** [sivoridaniel/serverapp#37]
Si hago un update de un usuario y no lo encuentra, rompe.

`[/AppServer/src/controller/AbmUserController.cpp:82]
05/29/16 23:08:28 [140072170781056] DEBUG UserLoginController %% - Actualizando usuario con id 45 [/AppServer/src/controller/AbmUserController.cpp:88]
terminate called after throwing an instance of 'EntityNotFoundException'
05/29/16 23:08:35 [140072170781056] DEBUG RemoteSharedService %% - Response code 404 [/AppServer/src/service/impl/RemoteSharedService.cpp:140]
05/29/16 23:08:35 [140072170781056] DEBUG RemoteSharedService %% - Response body {"success":false,"data":"Usuario Inexistente"} [/AppServer/src/service/impl/RemoteSharedService.cpp:141]
05/29/16 23:08:35 [140072170781056] WARN  RemoteSharedService %% - El usuario o interes no se encuentra registrado en el shared [/AppServer/src/service/impl/RemoteSharedService.cpp:144]
  what():  No se encuentra la entidad
`

**Comment by agulinari** [comment]
Resuelto
